@using Microsoft.AspNetCore.Components.Forms
@using Mini_CRM_Blazor.Shared.Models
@using MudBlazor
@using System.ComponentModel.DataAnnotations

@inject NavigationManager navigationManager
@inject CustomStateProvider authStateProvider

<EditForm OnValidSubmit="OnSubmit" Model="loginRequest">
    <DataAnnotationsValidator />
    <MudCard Elevation="0">
        <MudCardContent>
            <MudTextField Label="UserName"
                          Class="mt-3"
                          @bind-Value="loginRequest.UserName"
                          For="@(() => loginRequest.UserName)" />
            <ValidationMessage For="@(() => loginRequest.UserName)" />
            <MudTextField Label="Password"
                          HelperText="Choose a strong password"
                          Class="mt-3"
                          @bind-Value="loginRequest.Password"
                          For="@(() => loginRequest.Password)"
                          InputType="InputType.Password" />
            <ValidationMessage For="@(() => loginRequest.Password)" />
        </MudCardContent>
        <MudCardActions>
            <MudButton ButtonType="ButtonType.Submit"
                       Variant="Variant.Filled"
                       Color="Color.Primary"
                       DisableElevation="true"
                       Class="ml-auto">Log in</MudButton>
        </MudCardActions>
        <div class="form-check m-3">
            <InputCheckbox id="inputRememberMe" class="form-check-input" @bind-Value="loginRequest.RememberMe" />
            <label class="form-check-label" for="inputRememberMe">Remember Me</label>
        </div>
    </MudCard>
    <label class="text-danger">@error</label>
</EditForm>

@code {
    public LoginRequest loginRequest { get; set; } = new LoginRequest();
    string error { get; set; }
    bool success;

    async Task OnSubmit()
    {
        error = null;
        try
        {
            await authStateProvider.Login(loginRequest);
            navigationManager.NavigateTo("/dashboard");
        }
        catch (Exception ex)
        {
            error = ex.Message;
        }
    }
}